#!/usr/bin/env python3
"""Evaluate production color-classifier modes on clean hull-label samples.

The input JSONL is generated by the clean-label color-sample pipeline and
contains one row per sticker sample with a ground-truth color. This report is
the lightweight color-only calibration pass: it compares classifier modes,
surfaces high-confidence mistakes, and can render local contact sheets of the
most interesting sampled colors. Generated reports/contact sheets live under
``runs/`` and are intentionally ignored by git.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Sequence

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from rubik_recognizer.colors import (  # noqa: E402
    CLASSIFIER_CANONICAL,
    CLASSIFIER_KNN5_LAB,
    CLASSIFIER_KNN5_LAB_FULL,
    COLOR_ORDER,
    classify_rgb_with_mode,
)


DEFAULT_INPUT = ROOT / "runs" / "color_samples_geom.jsonl"
DEFAULT_OUTPUT = ROOT / "runs" / "color_classifier_modes_report.json"
DEFAULT_MARKDOWN_OUTPUT = ROOT / "runs" / "color_classifier_modes_report.md"
DEFAULT_CONTACT_SHEET_DIR = ROOT / "runs" / "color_classifier_contact_sheets"
RANKED_SAMPLE_LIMIT = 40
MODE_ORDER = (
    "canonical",
    "canonical_adaptive",
    "knn5_lab",
    "knn5_lab_adaptive",
    "knn5_lab_full",
    "knn5_lab_full_adaptive",
)
ADAPTIVE_CACHED_MODES = {"canonical_adaptive", "knn5_lab_adaptive", "knn5_lab_full_adaptive"}


def _mode_prediction(row: Dict[str, Any], mode: str) -> str:
    return str(_mode_prediction_detail(row, mode)["color"])


def _mode_prediction_detail(row: Mapping[str, Any], mode: str) -> Dict[str, Any]:
    rgb = tuple(int(value) for value in row["rgb"])
    if mode == "canonical":
        return _match_payload(classify_rgb_with_mode(rgb, CLASSIFIER_CANONICAL))
    if mode == "knn5_lab":
        return _match_payload(classify_rgb_with_mode(rgb, CLASSIFIER_KNN5_LAB))
    if mode == "knn5_lab_full":
        return _match_payload(classify_rgb_with_mode(rgb, CLASSIFIER_KNN5_LAB_FULL))
    modes = row.get("classifierModes")
    if mode in ADAPTIVE_CACHED_MODES and isinstance(modes, dict) and isinstance(modes.get(mode), str):
        return _cached_match_payload(str(modes[mode]))
    if mode == "canonical_adaptive" and isinstance(row.get("calibratedClassifier"), str):
        return _cached_match_payload(str(row["calibratedClassifier"]))
    if mode == "canonical" and isinstance(row.get("defaultClassifier"), str):
        return _cached_match_payload(str(row["defaultClassifier"]))
    raise ValueError(
        f"Input row lacks {mode!r}; regenerate with tools/extract_clean_dataset.py "
        "from this branch for adaptive-mode evaluation."
    )


def _match_payload(match: Any) -> Dict[str, Any]:
    if not hasattr(match, "alternatives"):
        return _cached_match_payload(str(match.color))
    second = match.alternatives[1][1] if len(match.alternatives) > 1 else match.distance
    return {
        "color": match.color,
        "confidence": round(float(match.confidence), 4),
        "distance": round(float(match.distance), 4),
        "margin": round(float(second - match.distance), 4),
        "alternatives": [
            {"color": color, "distance": round(float(distance), 4)}
            for color, distance in match.alternatives[:3]
        ],
    }


def _cached_match_payload(color: str) -> Dict[str, Any]:
    return {
        "color": color,
        "confidence": None,
        "distance": None,
        "margin": None,
        "alternatives": [],
    }


def _accuracy(rows: Sequence[Dict[str, Any]], mode: str) -> float:
    if not rows:
        return 0.0
    correct = sum(1 for row in rows if _mode_prediction(row, mode) == row["gtColor"])
    return correct / len(rows)


def _confusion(rows: Sequence[Dict[str, Any]], mode: str) -> List[List[int]]:
    index = {color: idx for idx, color in enumerate(COLOR_ORDER)}
    matrix = [[0 for _ in COLOR_ORDER] for _ in COLOR_ORDER]
    for row in rows:
        truth = row["gtColor"]
        pred = _mode_prediction(row, mode)
        matrix[index[truth]][index[pred]] += 1
    return matrix


def _confusion_pairs(rows: Sequence[Dict[str, Any]], mode: str) -> List[Dict[str, Any]]:
    counts: Counter[tuple[str, str]] = Counter()
    for row in rows:
        truth = row["gtColor"]
        pred = _mode_prediction(row, mode)
        if truth != pred:
            counts[(truth, pred)] += 1
    return [
        {"expected": expected, "predicted": predicted, "count": count}
        for (expected, predicted), count in sorted(
            counts.items(),
            key=lambda item: (-item[1], item[0][0], item[0][1]),
        )
    ]


def _per_color_accuracy(rows: Sequence[Dict[str, Any]], mode: str) -> Dict[str, float]:
    by_color: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for row in rows:
        by_color[row["gtColor"]].append(row)
    return {
        color: round(_accuracy(by_color.get(color, ()), mode), 4)
        for color in COLOR_ORDER
    }


def _per_set_accuracy(rows: Sequence[Dict[str, Any]], mode: str) -> Dict[str, float]:
    by_set: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for row in rows:
        by_set[str(row["setId"])].append(row)
    return {
        set_id: round(_accuracy(by_set[set_id], mode), 4)
        for set_id in sorted(by_set, key=lambda value: int(value) if value.isdigit() else value)
    }


def _mode_report(rows: Sequence[Dict[str, Any]], mode: str) -> Dict[str, Any]:
    return {
        "overallAccuracy": round(_accuracy(rows, mode), 4),
        "perColorAccuracy": _per_color_accuracy(rows, mode),
        "perSetAccuracy": _per_set_accuracy(rows, mode),
        "confusionLabels": list(COLOR_ORDER),
        "confusionMatrix": _confusion(rows, mode),
        "confusionPairs": _confusion_pairs(rows, mode),
        "highConfidenceMismatches": _ranked_mismatches(rows, mode, RANKED_SAMPLE_LIMIT),
        "weakestSamples": _weakest_samples(rows, mode, RANKED_SAMPLE_LIMIT),
    }


def _deltas(candidate: Dict[str, float], baseline: Dict[str, float]) -> Dict[str, float]:
    return {
        key: round(candidate.get(key, 0.0) - baseline.get(key, 0.0), 4)
        for key in baseline
    }


def _sample_label(row: Mapping[str, Any]) -> str:
    face = row.get("face") or row.get("labelName") or "?"
    pos = ""
    if "row" in row and "col" in row:
        pos = f"[{row['row']},{row['col']}]"
    return f"{row.get('setId', '?')}_{row.get('side', '?')} {face}{pos}"


def _sample_payload(row: Mapping[str, Any], mode: str) -> Dict[str, Any]:
    prediction = _mode_prediction_detail(row, mode)
    return {
        "sample": _sample_label(row),
        "setId": str(row.get("setId", "")),
        "side": str(row.get("side", "")),
        "face": str(row.get("face") or row.get("labelName") or ""),
        "row": row.get("row"),
        "col": row.get("col"),
        "isCenter": bool(row.get("isCenter")),
        "gtColor": row["gtColor"],
        "predictedColor": prediction["color"],
        "correct": prediction["color"] == row["gtColor"],
        "confidence": prediction["confidence"],
        "margin": prediction["margin"],
        "rgb": [int(value) for value in row["rgb"]],
        "alternatives": prediction["alternatives"],
    }


def _ranked_mismatches(rows: Sequence[Dict[str, Any]], mode: str, limit: int) -> List[Dict[str, Any]]:
    out = []
    for row in rows:
        payload = _sample_payload(row, mode)
        if payload["correct"]:
            continue
        out.append(payload)
    out.sort(key=lambda item: (
        -(float(item["confidence"]) if isinstance(item["confidence"], (int, float)) else -1.0),
        -(float(item["margin"]) if isinstance(item["margin"], (int, float)) else -1.0),
        item["sample"],
    ))
    return out[:limit]


def _weakest_samples(rows: Sequence[Dict[str, Any]], mode: str, limit: int) -> List[Dict[str, Any]]:
    out = [_sample_payload(row, mode) for row in rows]
    out.sort(key=lambda item: (
        float(item["confidence"]) if isinstance(item["confidence"], (int, float)) else 2.0,
        float(item["margin"]) if isinstance(item["margin"], (int, float)) else 999.0,
        item["sample"],
    ))
    return out[:limit]


def _head_to_head_samples(
    rows: Sequence[Dict[str, Any]],
    candidate_mode: str,
    baseline_mode: str = "canonical",
    limit: int = RANKED_SAMPLE_LIMIT,
) -> Dict[str, List[Dict[str, Any]]]:
    wins = []
    regressions = []
    for row in rows:
        truth = row["gtColor"]
        baseline = _mode_prediction_detail(row, baseline_mode)
        candidate = _mode_prediction_detail(row, candidate_mode)
        baseline_correct = baseline["color"] == truth
        candidate_correct = candidate["color"] == truth
        payload = _sample_payload(row, candidate_mode)
        payload["baselineColor"] = baseline["color"]
        payload["candidateColor"] = candidate["color"]
        if candidate_correct and not baseline_correct:
            wins.append(payload)
        elif baseline_correct and not candidate_correct:
            regressions.append(payload)
    wins.sort(key=lambda item: (item["sample"], item["gtColor"], item["candidateColor"]))
    regressions.sort(key=lambda item: (item["sample"], item["gtColor"], item["candidateColor"]))
    return {
        "candidateFixesBaseline": wins[:limit],
        "candidateRegressesBaseline": regressions[:limit],
    }


def _markdown_table(headers: Sequence[str], rows: Sequence[Sequence[Any]]) -> List[str]:
    out = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        out.append("| " + " | ".join(str(item) for item in row) + " |")
    return out


def _pct(value: float) -> str:
    return f"{value * 100:.1f}%"


def render_markdown_report(report: Mapping[str, Any]) -> str:
    lines: List[str] = [
        "# Color classifier mode report",
        "",
        f"Input: `{report['input']}`",
        f"Samples: {report['sampleCount']} across {report['setCount']} sets.",
        "",
        "## Mode accuracy",
    ]
    canonical_accuracy = report["modes"]["canonical"]["overallAccuracy"]
    mode_rows = []
    for mode in MODE_ORDER:
        accuracy = report["modes"][mode]["overallAccuracy"]
        mode_rows.append([
            f"`{mode}`",
            _pct(accuracy),
            f"{accuracy - canonical_accuracy:+.4f}",
        ])
    lines.extend(_markdown_table(["Mode", "Accuracy", "Delta vs canonical"], mode_rows))
    lines.extend(["", "## Accuracy by ground-truth color"])
    color_rows = []
    for color in COLOR_ORDER:
        color_rows.append([
            color,
            *[_pct(report["modes"][mode]["perColorAccuracy"][color]) for mode in MODE_ORDER],
        ])
    lines.extend(_markdown_table(["GT color", *[f"`{mode}`" for mode in MODE_ORDER]], color_rows))

    lines.extend(["", "## Canonical confusion pairs"])
    confusion_rows = [
        [row["expected"], row["predicted"], row["count"]]
        for row in report["modes"]["canonical"]["confusionPairs"][:15]
    ]
    lines.extend(_markdown_table(["Expected", "Predicted", "Count"], confusion_rows) if confusion_rows else ["No canonical mistakes."])

    lines.extend(["", "## Candidate modes vs canonical"])
    h2h_rows = []
    for mode in MODE_ORDER:
        if mode == "canonical":
            continue
        row = report["headToHead"][mode]
        h2h_rows.append([
            f"`{mode}`",
            row["wins"],
            row["losses"],
            row["ties"],
            len(row.get("candidateFixesBaseline", [])),
            len(row.get("candidateRegressesBaseline", [])),
        ])
    lines.extend(_markdown_table(
        ["Mode", "Set wins", "Set losses", "Set ties", "Sticker fixes shown", "Sticker regressions shown"],
        h2h_rows,
    ))

    lines.extend(["", "## Highest-confidence canonical mismatches"])
    mismatch_rows = []
    for row in report["modes"]["canonical"]["highConfidenceMismatches"][:20]:
        mismatch_rows.append([
            f"`{row['sample']}`",
            row["gtColor"],
            row["predictedColor"],
            row["confidence"],
            row["margin"],
            row["rgb"],
        ])
    lines.extend(_markdown_table(
        ["Sample", "Expected", "Predicted", "Confidence", "Margin", "RGB"],
        mismatch_rows,
    ) if mismatch_rows else ["No canonical mismatches."])

    lines.extend(["", "## Lowest-confidence canonical samples"])
    weak_rows = []
    for row in report["modes"]["canonical"]["weakestSamples"][:20]:
        weak_rows.append([
            f"`{row['sample']}`",
            row["gtColor"],
            row["predictedColor"],
            "yes" if row["correct"] else "no",
            row["confidence"],
            row["margin"],
            row["rgb"],
        ])
    lines.extend(_markdown_table(
        ["Sample", "Expected", "Predicted", "Correct", "Confidence", "Margin", "RGB"],
        weak_rows,
    ))

    contact_sheets = report.get("contactSheets") or {}
    if contact_sheets:
        lines.extend(["", "## Contact sheets"])
        for name, path in contact_sheets.items():
            lines.append(f"- `{name}`: `{path}`")

    lines.extend([
        "",
        "## Notes",
        "",
        "- Runtime modes (`canonical`, `knn5_lab`, `knn5_lab_full`) are recomputed from the current code.",
        "- Adaptive modes are read from cached extracted predictions because their palette is local to each extracted sample set.",
        "- Contact sheets are local diagnostic artifacts under `runs/`; they are not committed.",
    ])
    return "\n".join(lines) + "\n"


def _font(size: int) -> ImageFont.ImageFont:
    for path in (
        "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
    ):
        try:
            return ImageFont.truetype(path, size)
        except OSError:
            continue
    return ImageFont.load_default()


def _write_swatch_sheet(
    *,
    rows: Sequence[Mapping[str, Any]],
    output_path: Path,
    title: str,
    mode: str,
    columns: int = 5,
) -> Optional[Path]:
    if not rows:
        return None
    tile_w = 260
    tile_h = 138
    header_h = 44
    rows_count = (len(rows) + columns - 1) // columns
    image = Image.new("RGB", (columns * tile_w, header_h + rows_count * tile_h), (245, 245, 245))
    draw = ImageDraw.Draw(image)
    title_font = _font(18)
    text_font = _font(12)
    draw.text((12, 12), title, fill=(20, 20, 20), font=title_font)
    for index, row in enumerate(rows):
        x = (index % columns) * tile_w
        y = header_h + (index // columns) * tile_h
        rgb = tuple(int(value) for value in row["rgb"])
        draw.rectangle((x + 10, y + 12, x + 80, y + 82), fill=rgb, outline=(30, 30, 30), width=1)
        label = str(row.get("sample", ""))
        expected = row.get("gtColor")
        predicted = row.get("predictedColor") or row.get("candidateColor")
        baseline = row.get("baselineColor")
        lines = [
            label,
            f"{expected} -> {predicted}" + (f" (base {baseline})" if baseline else ""),
            f"conf={row.get('confidence')} margin={row.get('margin')}",
            f"rgb={list(rgb)}",
            f"mode={mode}",
        ]
        for offset, line in enumerate(lines):
            draw.text((x + 92, y + 12 + offset * 22), line[:26], fill=(25, 25, 25), font=text_font)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    image.save(output_path, quality=92)
    return output_path


def write_contact_sheets(report: Mapping[str, Any], output_dir: Path) -> Dict[str, str]:
    sheets: Dict[str, str] = {}
    canonical = report["modes"]["canonical"]
    rows = {
        "canonical_high_confidence_mismatches": canonical["highConfidenceMismatches"],
        "canonical_low_confidence_samples": canonical["weakestSamples"],
        "canonical_red_orange_confusions": [
            row
            for row in canonical["highConfidenceMismatches"]
            if {row["gtColor"], row["predictedColor"]} <= {"red", "orange"}
        ],
        "knn5_full_fixes_canonical": report["headToHead"]["knn5_lab_full"]["candidateFixesBaseline"],
        "knn5_full_regresses_canonical": report["headToHead"]["knn5_lab_full"]["candidateRegressesBaseline"],
    }
    for name, sample_rows in rows.items():
        path = _write_swatch_sheet(
            rows=sample_rows,
            output_path=output_dir / f"{name}.jpg",
            title=name.replace("_", " "),
            mode="canonical" if name.startswith("canonical") else "knn5_lab_full",
        )
        if path is not None:
            sheets[name] = str(path)
    return sheets


def _print_table(report: Dict[str, Any]) -> None:
    print("Mode                  Accuracy  Delta vs canonical")
    print("--------------------  --------  ------------------")
    canonical = report["modes"]["canonical"]["overallAccuracy"]
    for mode in MODE_ORDER:
        accuracy = report["modes"][mode]["overallAccuracy"]
        print(f"{mode:20s}  {accuracy:8.4f}  {accuracy - canonical:+18.4f}")

    for mode in MODE_ORDER[1:]:
        deltas = report["headToHead"][mode]["perSetDelta"]
        regressions = sorted(deltas.items(), key=lambda item: item[1])[:3]
        wins = sorted(deltas.items(), key=lambda item: item[1])[-3:]
        print(f"\n{mode} vs canonical:")
        print(f"  worst regressions: {regressions}")
        print(f"  biggest wins:      {wins}")


def _validate_rows(rows: Iterable[Dict[str, Any]]) -> List[Dict[str, Any]]:
    validated = []
    for row in rows:
        if row.get("gtColor") not in COLOR_ORDER:
            raise ValueError(f"Invalid gtColor in row: {row!r}")
        if not isinstance(row.get("rgb"), list) or len(row["rgb"]) != 3:
            raise ValueError(f"Invalid rgb in row: {row!r}")
        validated.append(row)
    return validated


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", default=str(DEFAULT_INPUT))
    parser.add_argument("--json-output", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--md-output", default=str(DEFAULT_MARKDOWN_OUTPUT))
    parser.add_argument("--contact-sheet-dir", default=str(DEFAULT_CONTACT_SHEET_DIR))
    parser.add_argument("--no-contact-sheets", action="store_true")
    args = parser.parse_args()

    input_path = Path(args.input)
    rows = _validate_rows(json.loads(line) for line in input_path.read_text().splitlines() if line.strip())
    if not rows:
        raise SystemExit("No clean-label samples found.")

    report: Dict[str, Any] = {
        "input": str(input_path),
        "sampleCount": len(rows),
        "setCount": len({row["setId"] for row in rows}),
        "colorCounts": dict(Counter(row["gtColor"] for row in rows)),
        "modes": {},
        "headToHead": {},
    }
    for mode in MODE_ORDER:
        report["modes"][mode] = _mode_report(rows, mode)

    baseline = report["modes"]["canonical"]["perSetAccuracy"]
    for mode in MODE_ORDER[1:]:
        per_set = report["modes"][mode]["perSetAccuracy"]
        deltas = _deltas(per_set, baseline)
        report["headToHead"][mode] = {
            "perSetDelta": deltas,
            "wins": sum(1 for delta in deltas.values() if delta > 0),
            "losses": sum(1 for delta in deltas.values() if delta < 0),
            "ties": sum(1 for delta in deltas.values() if delta == 0),
            **_head_to_head_samples(rows, mode),
        }

    if not args.no_contact_sheets:
        report["contactSheets"] = write_contact_sheets(report, Path(args.contact_sheet_dir))

    output_path = Path(args.json_output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    md_path = Path(args.md_output)
    md_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.write_text(render_markdown_report(report), encoding="utf-8")
    _print_table(report)
    print(f"\nwrote {output_path}")
    print(f"wrote {md_path}")
    if report.get("contactSheets"):
        print(f"wrote contact sheets under {Path(args.contact_sheet_dir)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
