#!/usr/bin/env python3
"""Projected cube model V0.

Diagnostics-only first-principles geometry scaffold.

The model is intentionally simple: one image-space cube-center point, three
projected cube-axis directions, and one shared edge length. From those, every
visible face quad and every visible sticker cell is generated by the same
coherent projected cube model.

This module does not classify colors and does not touch production recognizer
behavior. It exists to test the core invariant:

    No sampled sticker exists unless it belongs to one valid projected model.
"""

from __future__ import annotations

import itertools
import math
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
from PIL import Image, ImageDraw

from tools.interior_bezel_detection import InteriorBezelDetection


Point = Tuple[float, float]
Vector = Tuple[float, float]
Quad = List[Point]


FACE_PAIRS: Tuple[Tuple[int, int], ...] = ((0, 1), (1, 2), (2, 0))


@dataclass(frozen=True)
class ModelFace:
    """One visible projected cube face generated from two model axes."""

    name: str
    axis_pair: Tuple[int, int]
    quad: Quad
    cells: List[Dict[str, Any]]


@dataclass(frozen=True)
class ProjectedCubeModel:
    """A coherent 2D projection of the three visible cube faces."""

    cube_center: Point
    axes: Tuple[Vector, Vector, Vector]
    edge_length: float
    sign_choice: Tuple[int, int, int]
    faces: Tuple[ModelFace, ModelFace, ModelFace]
    score: float
    score_components: Dict[str, float]
    warnings: Tuple[str, ...] = field(default_factory=tuple)

    def all_cell_quads(self) -> List[Quad]:
        return [cell["quad"] for face in self.faces for cell in face.cells]

    def outer_vertices(self) -> List[Point]:
        """Return the six non-center model vertices used for overlay."""
        c = self.cube_center
        axis_points = [_add(c, axis) for axis in self.axes]
        far_points = [
            _add(c, _add_vec(self.axes[i], self.axes[j]))
            for i, j in FACE_PAIRS
        ]
        return axis_points + far_points


@dataclass(frozen=True)
class FitResult:
    """Fit wrapper that can represent an abstention."""

    model: Optional[ProjectedCubeModel]
    status: str
    diagnostics: Dict[str, Any]


def fit_projected_cube_model(
    detection: InteriorBezelDetection,
    silhouette_mask: np.ndarray,
    *,
    edge_steps: int = 32,
) -> FitResult:
    """Fit a V0 projected cube model against the silhouette.

    The search is deliberately small and interpretable:

    1. Use the interior-bezel detector's cube center and 3 line angles.
    2. Try all 2^3 axis sign choices because detector angles are unoriented.
    3. Search one shared edge length.
    4. Score the union of the 3 generated face quads against the rembg mask.

    This is not a production fitter. It is the first diagnostics scaffold for
    validating whether the global-model invariant is the right shape.
    """
    if silhouette_mask.ndim != 2:
        return FitResult(None, "invalid_mask", {"error": "silhouette_mask must be 2-D"})
    if detection.cube_center is None:
        return FitResult(None, "missing_center", {"error": "interior bezel detector has no cube_center"})
    if len(detection.boundary_angles) < 3:
        return FitResult(None, "missing_axes", {"error": "need 3 detected boundary angles"})
    if int(silhouette_mask.sum()) <= 0:
        return FitResult(None, "empty_mask", {"error": "silhouette mask is empty"})

    center = (float(detection.cube_center[0]), float(detection.cube_center[1]))
    base_units = [_unit_from_angle(angle) for angle in detection.boundary_angles[:3]]
    edge_min, edge_max = _edge_search_range(center, silhouette_mask)
    if edge_max <= edge_min:
        return FitResult(None, "invalid_search_range", {"edgeMin": edge_min, "edgeMax": edge_max})

    best: Optional[ProjectedCubeModel] = None
    evaluated = 0
    for signs in itertools.product((-1, 1), repeat=3):
        signed_units = [
            (sign * unit[0], sign * unit[1])
            for sign, unit in zip(signs, base_units)
        ]
        for edge_length in np.linspace(edge_min, edge_max, edge_steps):
            axes = tuple(
                (float(edge_length * unit[0]), float(edge_length * unit[1]))
                for unit in signed_units
            )
            model = _model_from_axes(
                center,
                axes,
                float(edge_length),
                tuple(int(sign) for sign in signs),
                silhouette_mask,
                detection,
            )
            evaluated += 1
            if best is None or model.score > best.score:
                best = model

    if best is None:
        return FitResult(None, "no_candidates", {"evaluatedCandidates": evaluated})
    status = "ok"
    if best.score_components.get("insideRatio", 0.0) < 0.70:
        status = "low_inside_ratio"
    elif best.score_components.get("silhouetteIoU", 0.0) < 0.55:
        status = "low_iou"
    elif best.score_components.get("cellInsideRatio", 0.0) < 0.90:
        status = "low_cell_inside"
    return FitResult(
        best,
        status,
        {
            "evaluatedCandidates": evaluated,
            "edgeMin": round(edge_min, 2),
            "edgeMax": round(edge_max, 2),
            "detectorSignalQuality": round(float(detection.signal_quality), 4),
            "detectorLineQualities": [round(float(q), 4) for q in detection.line_qualities],
        },
    )


def subdivide_face_quad(face_quad: Sequence[Point]) -> List[Dict[str, Any]]:
    """Generate 9 model-derived cell quads from one face quad."""
    if len(face_quad) != 4:
        raise ValueError("face_quad must contain exactly 4 points")
    quad = [(float(x), float(y)) for x, y in face_quad]
    cells: List[Dict[str, Any]] = []
    for row in range(3):
        v0 = row / 3.0
        v1 = (row + 1) / 3.0
        for col in range(3):
            u0 = col / 3.0
            u1 = (col + 1) / 3.0
            cells.append(
                {
                    "row": row,
                    "col": col,
                    "quad": [
                        bilinear_point(quad, u0, v0),
                        bilinear_point(quad, u1, v0),
                        bilinear_point(quad, u1, v1),
                        bilinear_point(quad, u0, v1),
                    ],
                }
            )
    return cells


def bilinear_point(quad: Sequence[Point], u: float, v: float) -> Point:
    a, b, c, d = quad
    x = (
        (1 - u) * (1 - v) * a[0]
        + u * (1 - v) * b[0]
        + u * v * c[0]
        + (1 - u) * v * d[0]
    )
    y = (
        (1 - u) * (1 - v) * a[1]
        + u * (1 - v) * b[1]
        + u * v * c[1]
        + (1 - u) * v * d[1]
    )
    return (float(x), float(y))


def model_mask(model: ProjectedCubeModel, shape: Tuple[int, int]) -> np.ndarray:
    """Rasterize the union of the model's 3 visible faces."""
    height, width = shape
    img = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(img)
    for face in model.faces:
        draw.polygon([(x, y) for x, y in face.quad], fill=255)
    return np.asarray(img, dtype=np.uint8) > 0


def serialize_model(model: ProjectedCubeModel) -> Dict[str, Any]:
    return {
        "cubeCenter": _round_point(model.cube_center),
        "axes": [_round_point(axis) for axis in model.axes],
        "edgeLength": round(model.edge_length, 3),
        "signChoice": list(model.sign_choice),
        "score": round(model.score, 4),
        "scoreComponents": {
            key: round(float(value), 4)
            for key, value in sorted(model.score_components.items())
        },
        "warnings": list(model.warnings),
        "faces": [
            {
                "name": face.name,
                "axisPair": list(face.axis_pair),
                "quad": [_round_point(point) for point in face.quad],
                "cellCount": len(face.cells),
            }
            for face in model.faces
        ],
    }


def _model_from_axes(
    center: Point,
    axes: Tuple[Vector, Vector, Vector],
    edge_length: float,
    signs: Tuple[int, int, int],
    silhouette_mask: np.ndarray,
    detection: InteriorBezelDetection,
) -> ProjectedCubeModel:
    face_objs: List[ModelFace] = []
    for i, j in FACE_PAIRS:
        quad = [
            center,
            _add(center, axes[i]),
            _add(center, _add_vec(axes[i], axes[j])),
            _add(center, axes[j]),
        ]
        face_objs.append(
            ModelFace(
                name=f"face_{i}{j}",
                axis_pair=(i, j),
                quad=quad,
                cells=subdivide_face_quad(quad),
            )
        )
    candidate = ProjectedCubeModel(
        cube_center=center,
        axes=axes,
        edge_length=edge_length,
        sign_choice=signs,
        faces=tuple(face_objs),  # type: ignore[arg-type]
        score=0.0,
        score_components={},
    )
    components = _score_components(candidate, silhouette_mask, detection)
    score = (
        components["silhouetteIoU"] * 1.0
        + components["insideRatio"] * 0.9
        + components["maskCoverage"] * 0.25
        + components["detectorSignalQuality"] * 0.15
        + components["cellInsideRatio"] * 0.25
        - components["outsideImagePenalty"] * 0.7
    )
    warnings: List[str] = []
    if components["insideRatio"] < 0.70:
        warnings.append("low_model_inside_silhouette")
    if components["silhouetteIoU"] < 0.55:
        warnings.append("low_silhouette_iou")
    if components["cellInsideRatio"] < 0.90:
        warnings.append("low_cell_inside_silhouette")
    return ProjectedCubeModel(
        cube_center=center,
        axes=axes,
        edge_length=edge_length,
        sign_choice=signs,
        faces=tuple(face_objs),  # type: ignore[arg-type]
        score=float(score),
        score_components=components,
        warnings=tuple(warnings),
    )


def _score_components(
    model: ProjectedCubeModel,
    silhouette_mask: np.ndarray,
    detection: InteriorBezelDetection,
) -> Dict[str, float]:
    mask = silhouette_mask.astype(bool)
    raster = model_mask(model, mask.shape)
    model_area = int(raster.sum())
    mask_area = int(mask.sum())
    intersection = int(np.logical_and(raster, mask).sum())
    union = int(np.logical_or(raster, mask).sum())
    inside_ratio = intersection / max(1, model_area)
    coverage = intersection / max(1, mask_area)
    iou = intersection / max(1, union)
    cell_centers = [_quad_centroid(cell) for cell in model.all_cell_quads()]
    cell_inside = _points_inside_mask(cell_centers, mask)
    outside_penalty = _outside_image_penalty(model, mask.shape)
    return {
        "silhouetteIoU": float(iou),
        "insideRatio": float(inside_ratio),
        "maskCoverage": float(coverage),
        "cellInsideRatio": float(cell_inside / max(1, len(cell_centers))),
        "detectorSignalQuality": float(detection.signal_quality),
        "outsideImagePenalty": float(outside_penalty),
    }


def _edge_search_range(center: Point, silhouette_mask: np.ndarray) -> Tuple[float, float]:
    ys, xs = np.where(silhouette_mask)
    if len(xs) == 0:
        return (0.0, 0.0)
    width = float(xs.max() - xs.min() + 1)
    height = float(ys.max() - ys.min() + 1)
    span = max(width, height)
    min_edge = max(24.0, span * 0.10)
    max_edge = max(min_edge + 1.0, span * 0.58)
    return (min_edge, max_edge)


def _unit_from_angle(angle: float) -> Vector:
    return (float(math.cos(angle)), float(math.sin(angle)))


def _add(left: Point, right: Vector) -> Point:
    return (float(left[0] + right[0]), float(left[1] + right[1]))


def _add_vec(left: Vector, right: Vector) -> Vector:
    return (float(left[0] + right[0]), float(left[1] + right[1]))


def _quad_centroid(quad: Sequence[Point]) -> Point:
    return (
        sum(point[0] for point in quad) / len(quad),
        sum(point[1] for point in quad) / len(quad),
    )


def _points_inside_mask(points: Sequence[Point], mask: np.ndarray) -> int:
    height, width = mask.shape
    count = 0
    for x, y in points:
        ix = int(round(x))
        iy = int(round(y))
        if 0 <= ix < width and 0 <= iy < height and bool(mask[iy, ix]):
            count += 1
    return count


def _outside_image_penalty(model: ProjectedCubeModel, shape: Tuple[int, int]) -> float:
    height, width = shape
    points: List[Point] = [model.cube_center]
    for face in model.faces:
        points.extend(face.quad)
    outside = 0
    for x, y in points:
        if not (0 <= x < width and 0 <= y < height):
            outside += 1
    return outside / max(1, len(points))


def _round_point(point: Point) -> List[float]:
    return [round(float(point[0]), 2), round(float(point[1]), 2)]
