#!/usr/bin/env python3
"""Validate the center-color CIELAB metric as a phase-hypothesis picker.

Diagnostic-only. Builds on the oracle rectified faces tool (PR #259/#260)
and the phase-parity diagnostic (PR #255).

## The hypothesis being tested

PR #255 showed that the production phase-correction detector is on net
hurting (modal: helped 2, hurt 3, no-flip 7, no-category-change 0). The
detector's input is pixel darkness along vertex->corner lines — a fairly
indirect signal. A more direct signal might be **center-color consistency**:
each face's center sticker is fixed (U=white, D=yellow, R=red, L=orange,
F=green, B=blue per the WCA convention encoded in `COLOR_TO_FACE`). If the
chirality detector's chosen face labeling is correct, the 3 visible center
stickers should match their expected canonical colors closely; if the
labeling is wrong (rotated 120 or 240 around the body diagonal), the
centers should be assigned to the wrong canonical colors and the distance
explodes.

This probe is the **precondition test**: does the metric
(sum of CIELAB distance from canonical color, summed over the 3 visible
centers on a side) reliably prefer the correct face-label permutation
over the two alternative cyclic permutations?

If YES on all 12 oracle rows, the metric is sound and a follow-up PR
can wire it into the production pipeline as a per-row gate
(run apply_phase_correction=True AND False, pick by this metric).

If NO, the metric is broken and we need to find a different orthogonal
signal — center-color is not strong enough on this cube color palette
under iPhone-photo conditions.

## What the probe does, concretely

1. Reads `/tmp/oracle_rectified_faces_v1/index.json` (generated by
   `tools/build_oracle_rectified_faces.py`).
2. For each row, extracts the 3 center stickers (sticker_id=5 per face).
3. Each center sticker has an oracle-validated `facelet_id` like "U5",
   "R5", "F5" — the LABELED face is the oracle's chirality assignment.
4. Computes 3 hypothesis scores using already-computed CIELAB values:
   - identity:    centers labeled per oracle (the "current chirality OK"
                  hypothesis) — Lab distance to canonical color of THAT face
   - cyclic_120:  rotate slot->face by 1 (the "if chirality were flipped one
                  way" hypothesis)
   - cyclic_240:  rotate slot->face by 2 (the other flip direction)
5. Per-row verdict: which hypothesis wins. Aggregate count.

## Why a pure-oracle probe first (not the production probe)

The oracle uses HUMAN-VALIDATED corner positions, so its face labeling is
guaranteed correct. If the metric can't reliably pick identity over
the two alternatives on this clean data, it definitely won't work on
the noisier production pipeline (which adds rembg + bezel detection +
PnP-fit uncertainty on top). Cheaper failure mode to find here than
after wiring up the production gate.

If identity reliably wins here, the follow-up PR exposes
`apply_phase_correction` on `fit_global_cube_model` and runs both
production hypotheses per row, scoring each by this same metric.
"""
from __future__ import annotations

import argparse
import json
import statistics
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from rubik_recognizer.colors import (  # noqa: E402
    CANONICAL_RGB,
    FACE_TO_COLOR,
    rgb_to_lab,
)


DEFAULT_INDEX = Path("/tmp/oracle_rectified_faces_v1/index.json")
DEFAULT_OUT_JSON = (
    REPO_ROOT / "tests" / "fixtures"
    / "center_color_phase_metric_trace.json"
)
DEFAULT_OUT_MD = (
    REPO_ROOT / "tools" / "CENTER_COLOR_PHASE_METRIC_REPORT.md"
)

# The current full-corner ground-truth fixture has 12 approved rows
# (6 sets x 2 sides). The probe's documented soundness claim is over
# this row count; running on a partial/empty oracle index without
# requiring the expected count would let a `green` report appear on
# 0/0 wins (vacuously true `all(...)` + `n_identity_wins == n_total`).
# Codex P2 on PR #262: require the count before declaring soundness.
DEFAULT_EXPECTED_ROWS = 12

CENTER_STICKER_ID = 5  # row=1, col=1 in URFDLB row-major numbering


# Pre-compute canonical Lab values for the 6 face centers so the
# per-sample inner loop is a constant-time lookup.
_CANONICAL_LAB_BY_FACE: Dict[str, Tuple[float, float, float]] = {
    face: rgb_to_lab(CANONICAL_RGB[color])
    for face, color in FACE_TO_COLOR.items()
}


def _lab_distance(
    a: Tuple[float, float, float], b: Tuple[float, float, float]
) -> float:
    """CIE76 Lab distance (Euclidean in L*a*b* space). PR #255-style
    diagnostic: rough perceptual distance, ~1 dE = "just noticeable".
    Sufficient for picking between 6 well-separated canonical colors;
    we deliberately do NOT use dE2000 here — the extra ~30 LOC of math
    buys nothing on a comparison this far above the JND threshold."""
    return (
        (a[0] - b[0]) ** 2
        + (a[1] - b[1]) ** 2
        + (a[2] - b[2]) ** 2
    ) ** 0.5


def _cycle_faces(
    slot_to_face: Sequence[str], shift: int
) -> Tuple[str, ...]:
    """Cycle the 3 face labels by `shift` slot positions.

    The chirality flip is a 120-degree rotation around the cube's
    body diagonal: it permutes the 3 visible faces at the trihedral
    vertex. shift=0 is identity; shift=1 is one 120-degree rotation;
    shift=2 is the other (240 = -120 mod 360).

    Implementation: rotate the (slot -> face) assignment by `shift`,
    which is equivalent to keeping the same image-pixel sticker
    positions and just relabeling them.
    """
    n = len(slot_to_face)
    return tuple(slot_to_face[(i + shift) % n] for i in range(n))


@dataclass
class CenterSample:
    slot: str
    oracle_face: str          # face label per oracle (e.g. "U")
    center_lab: Tuple[float, float, float]
    center_rgb: Tuple[int, int, int]


@dataclass
class RowHypothesisResult:
    key: str
    side: str
    yaw_quarter_turns: int
    oracle_face_assignment: Tuple[str, ...]
    hypothesis_scores: Dict[str, float]      # name -> total Lab dist
    hypothesis_face_assignments: Dict[str, Tuple[str, ...]]
    winning_hypothesis: str
    winning_score: float
    runner_up_hypothesis: str
    runner_up_score: float
    margin: float                            # runner_up - winning


def _extract_center(face_record: Dict[str, Any]) -> CenterSample:
    """Pull the center sticker (sticker_id=5) out of an oracle FaceRecord
    JSON entry."""
    center = next(
        s for s in face_record["stickers"]
        if s["sticker_id"] == CENTER_STICKER_ID
    )
    lab = tuple(float(v) for v in center["lab"])
    rgb = tuple(int(v) for v in center["rgb"])
    return CenterSample(
        slot=face_record["slot"],
        oracle_face=face_record["wca_face"],
        center_lab=lab,
        center_rgb=rgb,
    )


def _score_hypothesis(
    centers: Sequence[CenterSample],
    face_assignment: Sequence[str],
) -> float:
    """Sum CIELAB distance over the 3 centers, comparing each center's
    measured Lab to the canonical Lab of the face assigned to that slot."""
    total = 0.0
    for center, face in zip(centers, face_assignment):
        canonical_lab = _CANONICAL_LAB_BY_FACE[face]
        total += _lab_distance(center.center_lab, canonical_lab)
    return total


def evaluate_row(
    row_record: Dict[str, Any],
) -> RowHypothesisResult:
    """Score the 3 chirality hypotheses on one oracle row."""
    # Oracle gives faces in slot order (upper, right, front).
    faces_by_slot = {f["slot"]: f for f in row_record["faces"]}
    ordered_slots = ("upper", "right", "front")
    if not all(s in faces_by_slot for s in ordered_slots):
        raise ValueError(
            f"row {row_record['key']} missing one of upper/right/front: "
            f"have {list(faces_by_slot)}"
        )
    centers = [
        _extract_center(faces_by_slot[s]) for s in ordered_slots
    ]
    oracle_assignment = tuple(c.oracle_face for c in centers)
    hypotheses: Dict[str, Tuple[str, ...]] = {
        "identity": oracle_assignment,
        "cyclic_120": _cycle_faces(oracle_assignment, 1),
        "cyclic_240": _cycle_faces(oracle_assignment, 2),
    }
    scores: Dict[str, float] = {
        name: _score_hypothesis(centers, assign)
        for name, assign in hypotheses.items()
    }
    ranked = sorted(scores.items(), key=lambda kv: kv[1])
    winning_name, winning_score = ranked[0]
    runner_up_name, runner_up_score = ranked[1]
    return RowHypothesisResult(
        key=row_record["key"],
        side=row_record["side"],
        yaw_quarter_turns=row_record["yaw_quarter_turns"],
        oracle_face_assignment=oracle_assignment,
        hypothesis_scores=scores,
        hypothesis_face_assignments=hypotheses,
        winning_hypothesis=winning_name,
        winning_score=winning_score,
        runner_up_hypothesis=runner_up_name,
        runner_up_score=runner_up_score,
        margin=runner_up_score - winning_score,
    )


def evaluate_all(index: Dict[str, Any]) -> List[RowHypothesisResult]:
    rows = index.get("rows", [])
    return [evaluate_row(r) for r in rows]


# ---------------- report generation ----------------


def _serialize_result(r: RowHypothesisResult) -> Dict[str, Any]:
    return {
        "key": r.key,
        "side": r.side,
        "yaw_quarter_turns": r.yaw_quarter_turns,
        "oracle_face_assignment": list(r.oracle_face_assignment),
        "hypothesis_scores": {
            name: round(score, 2)
            for name, score in r.hypothesis_scores.items()
        },
        "hypothesis_face_assignments": {
            name: list(assign)
            for name, assign in r.hypothesis_face_assignments.items()
        },
        "winning_hypothesis": r.winning_hypothesis,
        "winning_score": round(r.winning_score, 2),
        "runner_up_hypothesis": r.runner_up_hypothesis,
        "runner_up_score": round(r.runner_up_score, 2),
        "margin": round(r.margin, 2),
    }


def render_report(
    results: List[RowHypothesisResult],
    expected_rows: Optional[int] = None,
) -> str:
    """Produce a human-readable Markdown summary of per-row + aggregate
    findings.

    `expected_rows`, if set, pins the probe's soundness claim to a
    specific row count — when the actual count differs (including the
    empty / partially-generated index case), the verdict surfaces as
    INCOMPLETE rather than claiming soundness. Codex P2 on PR #262.
    """
    lines: List[str] = []
    lines.append("# Center-color phase metric — validation report")
    lines.append("")
    lines.append(
        "Diagnostic-only. Tests whether sum-of-CIELAB-distance from "
        "canonical Rubik's colors, computed over the 3 visible center "
        "stickers per side, reliably prefers the **correct** face "
        "labeling (per oracle / human-validated yaw + corners) over "
        "the two alternative 120°-rotated hypotheses that the chirality "
        "detector might otherwise pick."
    )
    lines.append("")
    lines.append("Each row has 3 hypothesis scores:")
    lines.append("")
    lines.append(
        "- `identity` — slots labeled per oracle "
        "(the correct chirality assignment)"
    )
    lines.append(
        "- `cyclic_120` — slot->face assignment rotated 120° "
        "around the body diagonal"
    )
    lines.append(
        "- `cyclic_240` — slot->face assignment rotated 240° "
        "(equivalent to -120°)"
    )
    lines.append("")
    lines.append(
        "Lower score = better match to canonical colors. The metric "
        "is sound iff `identity` wins on all 12 rows by a clear margin."
    )
    lines.append("")

    # Headline counts
    n_total = len(results)
    n_identity_wins = sum(
        1 for r in results if r.winning_hypothesis == "identity"
    )
    n_strict_wins = sum(
        1 for r in results
        if r.winning_hypothesis == "identity" and r.margin > 0
    )
    margins_when_identity_wins = [
        r.margin for r in results if r.winning_hypothesis == "identity"
    ]
    margins_when_identity_loses = [
        r.hypothesis_scores["identity"] - r.winning_score
        for r in results if r.winning_hypothesis != "identity"
    ]

    lines.append("## Headline")
    lines.append("")
    lines.append(
        f"- `identity` wins on **{n_identity_wins}/{n_total}** rows"
    )
    lines.append(
        f"- Of those, **{n_strict_wins}** wins are strict "
        f"(margin > 0; the rest are ties)"
    )
    if margins_when_identity_wins:
        lines.append(
            f"- Margin when identity wins: "
            f"median {statistics.median(margins_when_identity_wins):.1f}, "
            f"min {min(margins_when_identity_wins):.1f}, "
            f"max {max(margins_when_identity_wins):.1f}"
        )
    if margins_when_identity_loses:
        lines.append(
            f"- Margin BY WHICH identity loses (when it loses): "
            f"median {statistics.median(margins_when_identity_loses):.1f}, "
            f"min {min(margins_when_identity_loses):.1f}, "
            f"max {max(margins_when_identity_loses):.1f}"
        )
    lines.append("")

    # Verdict — fail-closed on empty input and on partial input vs
    # the expected row count. Codex P2 on PR #262: without these
    # guards `n_identity_wins == n_total and all(...)` is vacuously
    # true on 0 results, so an empty / partially-generated oracle
    # index would print a green "Metric is sound" report.
    if n_total == 0:
        verdict = (
            "**Validation INCOMPLETE.** No results to evaluate — the "
            "oracle index appears empty. Soundness cannot be claimed "
            "on zero observations; check that "
            "`tools/build_oracle_rectified_faces.py` produced its "
            "expected output and rerun."
        )
    elif expected_rows is not None and n_total != expected_rows:
        verdict = (
            f"**Validation INCOMPLETE.** Got {n_total} rows but "
            f"expected {expected_rows} (the full-corner ground-truth "
            "fixture's documented row count). Soundness cannot be "
            "claimed on partial input — even a perfect score on a "
            "subset doesn't validate the documented precondition. "
            "Regenerate the oracle index over all approved rows, or "
            "set --expected-rows explicitly if reducing scope on "
            "purpose."
        )
    elif n_identity_wins == n_total and all(r.margin > 0 for r in results):
        verdict = (
            "**Metric is sound.** Identity wins strictly on all rows. "
            "Safe to wire into the production pipeline as a per-row "
            "phase-correction gate."
        )
    elif n_identity_wins == n_total:
        verdict = (
            "**Metric is sound but soft.** Identity wins (or ties) on "
            "all rows, but some margins are zero. Production use is "
            "viable but a tie-breaker secondary signal may be needed."
        )
    elif n_identity_wins >= n_total - 1:
        verdict = (
            "**Metric is mostly sound.** Identity wins on all but "
            f"{n_total - n_identity_wins} rows. Investigate the "
            "failing case(s) before relying on this as the only signal."
        )
    else:
        verdict = (
            "**Metric is NOT sound.** Identity loses on "
            f"{n_total - n_identity_wins}/{n_total} rows. Center-color "
            "alone is not strong enough; need additional orthogonal "
            "evidence."
        )
    lines.append(f"## Verdict\n\n{verdict}")
    lines.append("")

    # Per-row table
    lines.append("## Per-row scores")
    lines.append("")
    lines.append(
        "| Row | Yaw | Oracle (upper,right,front) | id | cyc120 | cyc240 | Winner | Margin |"
    )
    lines.append(
        "|---|---:|---|---:|---:|---:|---|---:|"
    )
    for r in results:
        oracle_str = ",".join(r.oracle_face_assignment)
        scores = r.hypothesis_scores
        flag = "" if r.winning_hypothesis == "identity" else " ⚠️"
        lines.append(
            f"| `{r.key}` | {r.yaw_quarter_turns} | {oracle_str} "
            f"| {scores['identity']:.1f} "
            f"| {scores['cyclic_120']:.1f} "
            f"| {scores['cyclic_240']:.1f} "
            f"| {r.winning_hypothesis}{flag} "
            f"| {r.margin:.1f} |"
        )
    lines.append("")

    # Sample-level intuition
    lines.append("## Where the margin comes from")
    lines.append("")
    lines.append(
        "For each row, the identity hypothesis assigns each center "
        "sticker to its canonical color (e.g. U center → white). The "
        "alternative hypotheses assign that same center pixel to a "
        "different canonical color (e.g. U center → red), producing a "
        "much larger Lab distance because the actual center color is "
        "nowhere near red. The metric works because the 6 canonical "
        "Rubik's colors are well separated in Lab space (median pairwise "
        f"distance ≈ {_median_canonical_pairwise_distance():.0f}), much "
        "larger than the per-row within-face color variation due to "
        "lighting / wear."
    )
    lines.append("")

    return "\n".join(lines)


def _median_canonical_pairwise_distance() -> float:
    """Helper for the report — distinguish a 'tight' palette (where the
    metric is fragile) from a 'spacious' one (robust)."""
    labs = list(_CANONICAL_LAB_BY_FACE.values())
    pairwise: List[float] = []
    for i in range(len(labs)):
        for j in range(i + 1, len(labs)):
            pairwise.append(_lab_distance(labs[i], labs[j]))
    return statistics.median(pairwise)


# ---------------- orchestration ----------------


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--index", type=Path, default=DEFAULT_INDEX,
        help="Oracle index.json (default /tmp/oracle_rectified_faces_v1/index.json).",
    )
    ap.add_argument(
        "--out-json", type=Path, default=DEFAULT_OUT_JSON,
        help="Per-row trace + summary JSON.",
    )
    ap.add_argument(
        "--out-md", type=Path, default=DEFAULT_OUT_MD,
        help="Human-readable markdown report.",
    )
    ap.add_argument(
        "--expected-rows", type=int, default=DEFAULT_EXPECTED_ROWS,
        help=(
            f"Expected number of rows in the oracle index (default "
            f"{DEFAULT_EXPECTED_ROWS} — the full-corner ground-truth "
            "fixture's row count). When the actual count differs, the "
            "verdict surfaces as INCOMPLETE and main() exits non-zero. "
            "Pass 0 to disable the check (e.g. for ad-hoc smaller runs)."
        ),
    )
    args = ap.parse_args(list(argv) if argv is not None else None)
    if not args.index.exists():
        print(
            f"error: oracle index not found at {args.index}\n"
            f"run tools/build_oracle_rectified_faces.py first.",
            file=sys.stderr,
        )
        return 1
    index = json.loads(args.index.read_text(encoding="utf-8"))
    results = evaluate_all(index)
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    # Translate `--expected-rows 0` to None (disabled). Any positive
    # value remains the pinned count. Negative values are nonsensical;
    # argparse + int() permits them but treat <=0 as "no check".
    expected_rows = args.expected_rows if args.expected_rows > 0 else None
    payload = {
        "schema": "center_color_phase_metric_v1",
        "source_index": str(args.index),
        "expected_rows": expected_rows,
        "n_rows": len(results),
        "n_identity_wins": sum(
            1 for r in results if r.winning_hypothesis == "identity"
        ),
        "results": [_serialize_result(r) for r in results],
    }
    args.out_json.write_text(
        json.dumps(payload, indent=2), encoding="utf-8"
    )
    args.out_md.parent.mkdir(parents=True, exist_ok=True)
    args.out_md.write_text(
        render_report(results, expected_rows=expected_rows),
        encoding="utf-8",
    )
    # Fail-closed exit code when the documented precondition isn't met
    # (empty index, or row count != expected). Codex P2 on PR #262.
    is_incomplete = (
        len(results) == 0
        or (expected_rows is not None and len(results) != expected_rows)
    )
    status = "INCOMPLETE" if is_incomplete else "ok"
    print(
        f"wrote {args.out_json} and {args.out_md} "
        f"({payload['n_identity_wins']}/{payload['n_rows']} identity wins; "
        f"{status})",
        file=sys.stderr,
    )
    return 2 if is_incomplete else 0


if __name__ == "__main__":
    raise SystemExit(main())
